### ISSUE TITLE
NaN value in S-map

### ISSUE THREAD

**Issue by neuronphysics** [joergdietrich/mapmap#1]
Hi, 

Thanks for your public weak-lensing aperture mass code.I am trying to use your code to make kappa map and signal-to-noise map. The code generates the kappa map and it looks reasonable but when I set "SMAP" parameter equal to "Y", it returns a map which all the values of S-map are NaN. I have been fiddling around with the input parameters but I couldn't figure out what might cause the problem. I will appreciate for any tip..  Thanks in advance.

**Comment by joergdietrich** [comment]
I need a bit more info to be able to reproduce your problem. Can you append your config and the first 20 lines or so of your shear catalog?

**Comment by neuronphysics** [comment]
Thanks a lot. It is my whole config file:

#------------------------------ Cosmology --------------------------------------
HUBBLE        0.7    # scaled Hubble constant H_0 = 100 h km/s/Mpc
OMEGA_MATTER  0.3    # Matter density
OMEGA_LAMBDA  0.7    # Cosmological constant

#---------------------------- Cluster Model ------------------------------------
PIXEL_SIZE     50    # Pixel size in kpc
REDSHIFT       0.128 # Redshift of fiducial cluster model
FILTER         SCHIRMER # The type of filter function
FILTER_RADIUS  1600  # Filter radius in kpc
FILTER_FILE    NONE  # File to read if FILTER == FILE
OVERSHOOT      1.0   # The filter function is applied out to OVERSHOOT*FILTER_RADIUS
SCHIRMER_XC    0.16  # xc value in Schirmer filter

#---------------------------- Input Catalog ------------------------------------
TABLE         OBJECTS     # Table name containing the galaxies
RA            ALPHA_J2000 # Column name for right ascencion
DEC           DELTA_J2000 # Column name for declination
E1            e1iso       # Column name for e1 component
E2            e2iso       # Column name for e2 component
WEIGHT        Y           # Weigh ellipticity values
WEIGHT_NAME   Sigmae      # Column name for weight
TOMOGRAPHY    N           # Perform weak lensing tomography
Z_NAME        z           # Column name for redshift

#---------------------------- Program Setup ------------------------------------
OUTPUT        map_50_0.16 # Default output basename
MAP_SUFFIX    _map_1600        # Suffix for Map maps
SMAP          Y           # Make significance map
SMAP_SUFFIX   _smap       # Suffix for significance maps
CROSS         N           # Rotate all ellipticities by 45 deg
CROSS_SUFFIX  _cross      # Suffix for cross-component images
INVERT        N           # Output inverted (negative) images
INVERT_SUFFIX _invert     # Suffix for inverted images
MOCK          N           # Create mock field (random rotation)
MOCK_SUFFIX   _mock       # Suffix for mock images
ZMIN          0.14        # Minimum redshift for tomography
ZMAX          1.5         # Maximum redshift for tomography
N_PLANES      15          # Number of redshift planes
VERBOSE       3           # Verbosity of output
NTHREADS      0           # Number of OpenMP threads (0: use system default)

The ascii file of my data 
24.9851162 -10.4479710 -0.1781500 -0.0473200 0.2335600 0.3880000
24.5923920 -10.4481089 0.2263000 -0.0095600 0.3107000 0.2500000
24.7729278 -10.4477457 0.0402800 0.1085200 0.2373000 0.4620000
24.9807342 -10.4478975 0.1074700 -0.1158400 0.3499900 0.5810000
24.6396556 -10.4482837 -0.1832700 -0.2054500 0.2849100 0.7220000
25.0114405 -10.4481192 0.1419500 -0.1486500 0.4626100 0.3570000
24.9860100 -10.4459622 0.1828000 0.2119900 0.4209600 0.5150000
24.9457409 -10.4481446 0.1951300 0.3511200 0.4217800 0.8920000
24.5994766 -10.4476412 -0.1152200 0.1952300 0.3532100 0.5990000

then I convert it to a fits ldac file with the following lines:

```
      CMD=P_ASCTOLDAC+' -i '+file_ascii+' -o ldac_intermediate.cat -t OBJECTS -c '+LDACCONF
      print>>sys.stderr,CMD+"\n"
      S.call([CMD],shell=True)
      CMD=P_LDACDELKEY+' -i ldac_intermediate.cat -o '+file_ldac+' -t OBJECTS -k FIELD_POS'
      print>>sys.stderr,CMD+"\n"
      S.call([CMD],shell=True)
```

**Comment by neuronphysics** [comment]
Hi again,

I am also wondering about the scaling of the kappa-map and signal-to-noise map?? It is not quite similar to other codes. Could you please explain how they can be interpreted?

**Comment by joergdietrich** [comment]
The fitler functions are not normalized to unity. Thus the scaling is arbitrary. The SNR maps are just that.

**Comment by joergdietrich** [comment]
Closed per our email exchange.
